### ISSUE TITLE
Small change to protocol

### ISSUE THREAD

**Issue by ccheever** [jacob-ebey/DigitimateSharp#1]
Hi-

Sorry to make this change but I think it's better to make it now rather than later.
I changed the protocol so that there is no longer a `success` field in responses.
Instead `err` is always sent and is explicitly null if everything is OK, or a descriptive string if there is an error.

I was worried people checking code would get confused if they saw `success: true` on an invalid code.

I'll submit a pull request later tonight if you don't have time to fix this.

**Comment by jacob-ebey** [comment]
If you could post a success and failure response for both send and check here I can pound it out and it would be good for documentation to reduce questions/confusion later.

**Comment by ccheever** [comment]
Hi-

You can always try out things on the site by just filling out the fields and clicking the try it button. It will populate a textarea with the response in JSON format.

Here are some examples though:
1. Successfully sending a code.

``` json
{"err":null,"userMobileNumber":"650-521-6131"}
```
1. Failure to send a code

``` json
{"err":"Bad Request: `userMobileNumber` must be at least 5 digits long"}
```
1. Successfully checking a valid, correct code

``` json
{"err":null,"validCode":true,"userMobileNumber":"650-521-6131"}
```
1. Successfully checking an _invalid_ code

``` json
{"err":null,"validCode":false,"userMobileNumber":"650-521-6131"}
```

(Since `err` is null, it means there was no problem with the server or the call you made; the user just entered and incorrect code.)
1. Unsuccessfully checking a code

``` json
{"err":"Bad Request: `userMobileNumber` must be at least 5 digits long"}
```

In this case, there was something wrong with the request or the server (the database is down, you sent an incorrect request, etc. etc.), and so we can't tell if the user's code was valid or not. So, `err` is populated with an error string, and `validCode` is not populated at all.

**Comment by jacob-ebey** [comment]
I'll make those changes real quick.

**Comment by jacob-ebey** [comment]
Updated to reflect protocol changes. I have incremented the minor version as it was a breaking change for backward compatibility of the library.
